name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git user
      shell: bash
      run: |
        git config --global user.email "hirotomo.yamada@avap.co.jp"
        git config --global user.name "hirotomoyamada"

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
